# This is a basic workflow to help you get started with Actions

name: Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.19.x'
          
      - name: Setup clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: Setup Dependencies
        run: install_deps.bat
        
      - name: Configure CMake
        run: cmake -Bbuild/x64/windows -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=x64-windows
        
      - name: Build Debug
        run: cmake --build build/x64/windows --config Debug
