# This is a basic workflow to help you get started with Actions

name: Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.19.x'

      - name: Setup clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup vcpkg
        run: cmd /c bootstrap-vcpkg.bat
        working-directory: ./vcpkg

      - name: Setup Dependencies
        run: cmd /c install_deps.bat

      - name: Configure CMake x64 Windows
        run: cmake -Bbuild/x64/windows -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build x64 Windows Debug
        run: cmake --build build/x64/windows --config Debug

      - name: Build x64 Windows RelWithDebInfo
        run: cmake --build build/x64/windows --config RelWithDebInfo

      - name: Build x64 Windows Release
        run: cmake --build build/x64/windows --config Release

      - name: Configure CMake x64 Windows Static
        run: cmake -Bbuild/x64/windows-static -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=x64-windows-static

      - name: Build x64 Windows Debug Static
        run: cmake --build build/x64/windows-static --config Debug

      - name: Build x64 Windows RelWithDebInfo Static
        run: cmake --build build/x64/windows-static --config RelWithDebInfo

      - name: Build x64 Windows Release Static
        run: cmake --build build/x64/windows-static --config Release
  
  build-linux-x64:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.0.3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.19.x'

      - name: Setup clang
        uses: egor-tensin/setup-clang@v1

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: Setup vcpkg
        run: ./bootstrap-vcpkg.sh
        working-directory: ./vcpkg

      - name: Setup Dependencies
        run: |
          chmod +x ./install_deps_linux.sh
          ./install_deps_linux.sh

      - name: Configure CMake x64 Linux
        run: cmake -Bbuild/x64/linux -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=x64-linux

      - name: Build x64 Linux Debug
        run: cmake --build build/x64/linux --config Debug

      - name: Build x64 Linux RelWithDebInfo
        run: cmake --build build/x64/linux --config RelWithDebInfo

      - name: Build x64 Linux Release
        run: cmake --build build/x64/linux --config Release

  build-android-arm64-x64-on-windows-x64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Install Android NDK
        run: '%ANDROID_HOME%/cmdline-tools/3.0/bin/sdkmanager.bat --install "ndk;23.0.7599858"'
        shell: cmd
      
      - name: Install Android Build Tools
        run: '%ANDROID_HOME%/cmdline-tools/3.0/bin/sdkmanager.bat --install build-tools;29.0.3'
        shell: cmd
        
      - name: Install Android 29
        run: '%ANDROID_HOME%/cmdline-tools/3.0/bin/sdkmanager.bat --install platforms;android-29'
        shell: cmd

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.19.x'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup vcpkg
        run: cmd /c bootstrap-vcpkg.bat
        working-directory: ./vcpkg

      - name: Setup Dependencies
        run: cmd /c install_android_deps.bat

      - name: Configure CMake arm64 Android
        run: cmake -Bbuild/arm64/android -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=arm64-android -DANDROID_PLATFORM=android-29 -DANDROID_ABI=arm64-v8a -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="$env:GITHUB_WORKSPACE/vcpkg/scripts/toolchains/android.cmake"
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      - name: Build arm64 Android Debug
        run: cmake --build build/arm64/android --config Debug
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      - name: Build arm64 Android RelWithDebInfo
        run: cmake --build build/arm64/android --config RelWithDebInfo
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      - name: Build arm64 Android Release
        run: cmake --build build/arm64/android --config Release
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      - name: Install arm64 Android Release
        run: cmake --build build/arm64/android --config Release --target install
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      - name: Package arm64 Android Release
        run: cmake --build build/arm64/android --config Release --target package
        env: 
          ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858

      #- name: Configure CMake x64 Android
      #  run: cmake -Bbuild/x64/android -G"Ninja Multi-Config" -DVCPKG_TARGET_TRIPLET=x64-android -DANDROID_PLATFORM=android-29 -DANDROID_ABI=arm64-v8a -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE="$env:GITHUB_WORKSPACE/vcpkg/scripts/toolchains/android.cmake"
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
      #- name: Build x64 Android Debug
      #  run: cmake --build build/x64/android --config Debug
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
      #- name: Build x64 Android RelWithDebInfo
      #  run: cmake --build build/x64/android --config RelWithDebInfo
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
      #- name: Build x64 Android Release
      #  run: cmake --build build/x64/android --config Release
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
      #- name: Install x64 Android Release
      #  run: cmake --build build/x64/android --config Release --target install
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
      #- name: Package x64 Android Relase
      #  run: cmake --build build/x64/android --config Release --target package
      #  env: 
      #    ANDROID_NDK_HOME: ${{env.ANDROID_HOME}}/ndk/23.0.7599858
